;;; -*- lexical-binding: t -*-

;; Define Ashen theme
(deftheme ashen "Ashen color scheme")

(let ((dark-background "#121212")
      (dark-gray "#191919")
      (selection-gray "#212121")
      (comment-gray "#535353")
      (mid-gray "#949494")
      (foreground "#a7a7a7")
      (light-foreground "#b4b4b4")
      (light-background "#d5d5d5")
      (red-ember "#b14242")
      (blue "#4a8b8b")
      (orange-blaze "#c4693d")
      (red-glowing "#df6464")
      (orange-smolder "#e49a44")
       (orange-glow "#d87c4a")
        (brown "#89492a")
        (g-1 "#e5e5e5")
        (g-2 "#d5d5d5")
        (g-3 "#b4b4b4")
        (g-4 "#a7a7a7")
        (g-5 "#949494")
        (g-6 "#737373")
        (g-7 "#535353")
        (g-8 "#323232")
        (g-9 "#212121")
        (orange-muted "#6D3B22")
        (red-flame "#C53030")
        (orange-golden "#E5A72A"))

  (custom-theme-set-faces
   'ashen
   `(default ((t (:foreground ,foreground :background ,dark-background))))
   `(cursor ((t (:background ,red-ember))))
   `(fringe ((t (:background ,dark-gray))))
   `(region ((t (:background ,selection-gray))))
   `(highlight ((t (:background ,dark-gray))))
   `(minibuffer-prompt ((t (:foreground ,blue :weight bold))))
     `(font-lock-builtin-face ((t (:foreground ,blue))))
     `(font-lock-comment-face ((t (:foreground ,g-6 :slant italic))))
     `(font-lock-comment-delimiter-face ((t (:foreground ,g-6 :slant italic))))
     `(font-lock-constant-face ((t (:foreground ,blue))))
     `(font-lock-function-name-face ((t (:foreground ,light-foreground :weight bold))))
     `(font-lock-function-call-face ((t (:foreground ,light-foreground))))
     `(font-lock-variable-name-face ((t (:foreground ,light-foreground))))
     `(font-lock-variable-use-face ((t (:foreground ,light-foreground))))
     `(font-lock-keyword-face ((t (:foreground ,red-ember))))
     `(font-lock-string-face ((t (:foreground ,red-glowing))))
     `(font-lock-doc-face ((t (:foreground ,red-glowing))))
     `(font-lock-doc-markup-face ((t (:foreground ,orange-smolder))))
     `(font-lock-type-face ((t (:foreground ,blue))))
     `(font-lock-number-face ((t (:foreground ,blue))))
     `(font-lock-operator-face ((t (:foreground ,orange-blaze))))
     `(font-lock-delimiter-face ((t (:foreground ,orange-smolder))))
     `(font-lock-bracket-face ((t (:foreground ,g-6))))
     `(font-lock-punctuation-face ((t (:foreground ,g-2))))
     `(font-lock-misc-punctuation-face ((t (:foreground ,orange-golden))))
     `(font-lock-escape-face ((t (:foreground ,orange-smolder))))
     `(font-lock-negation-char-face ((t (:foreground ,orange-blaze))))
     `(font-lock-property-name-face ((t (:foreground ,g-4))))
     `(font-lock-property-use-face ((t (:foreground ,g-4))))
     `(font-lock-preprocessor-face ((t (:foreground ,orange-smolder))))
   `(mode-line ((t (:foreground ,foreground :background ,selection-gray))))
   `(mode-line-inactive ((t (:foreground ,comment-gray :background ,dark-gray))))
    `(line-number ((t (:foreground ,g-8 :background ,dark-gray))))
   `(line-number-current-line ((t (:foreground ,foreground :background ,selection-gray))))
   `(dired-directory ((t (:foreground ,orange-glow))))
   `(dired-symlink ((t (:foreground ,red-ember))))
   `(dired-ignored ((t (:foreground ,comment-gray))))
    `(org-level-1 ((t (:foreground ,orange-glow :weight bold))))
   `(org-level-2 ((t (:foreground ,orange-blaze))))
   `(org-level-3 ((t (:foreground ,orange-glow))))
   `(org-block ((t (:background ,dark-gray))))
   `(org-code ((t (:foreground ,orange-blaze))))
    `(error ((t (:foreground ,red-flame :weight bold))))
    `(warning ((t (:foreground ,orange-golden :weight bold))))
    `(success ((t (:foreground ,orange-blaze :weight bold))))
   `(isearch ((t (:foreground ,orange-blaze :background ,dark-gray :inverse-video t))))
   `(lazy-highlight ((t (:foreground ,orange-smolder :background ,dark-gray :inverse-video t))))
     `(link ((t (:foreground ,blue :underline t))))
     `(link-visited ((t (:foreground ,red-ember :underline t))))
     `(show-paren-match ((t (:background ,orange-smolder :foreground ,dark-background))))
     `(show-paren-mismatch ((t (:background ,red-flame :foreground ,dark-background))))
      `(eglot-inlay-hint-face ((t (:foreground ,g-6 :height 0.8 :slant italic))))
     `(eglot-type-hint-face ((t (:inherit eglot-inlay-hint-face))))
     `(eglot-parameter-hint-face ((t (:inherit eglot-inlay-hint-face))))
     `(tree-sitter-hl-face:number ((t (:foreground ,blue))))
     `(tree-sitter-hl-face:string ((t (:foreground ,red-glowing))))
     `(tree-sitter-hl-face:operator ((t (:foreground ,orange-blaze))))
     `(tree-sitter-hl-face:delimiter ((t (:foreground ,orange-smolder))))
     `(tree-sitter-hl-face:bracket ((t (:foreground ,g-6))))
     `(tree-sitter-hl-face:punctuation ((t (:foreground ,g-2))))
     `(tree-sitter-hl-face:punctuation.special ((t (:foreground ,orange-golden))))))


(provide-theme 'ashen)
